services:
    server:
        image: express-docker
        ports: 
            - 5050:5000
    mongodb:
        image: mongo
    app: 
        image: client
        ports:
            - 8080:3000   


